name: ChatMaster
version: '1.0'
main: dev.hyperlisk.chatmaster.ChatMaster
api-version: '1.20'
commands:
  whisper:
    description: A command to whisper to an online player
    aliases: [w, wh]
    usage: "/<command> <player>"
    permission: chatmaster.whisper
  group:
    description: A command to set the group of a player and send a message to the group
    aliases: [g, gr]
    usage: "/<command> <group>"
    permission: chatmaster.group
