name: ChatMaster
version: '1.0'
main: dev.hyperlisk.chatmaster.ChatMaster
api-version: '1.20'
commands:
  whisper:
    description: Whisper command
    aliases: [w, wh]
    usage: "/<command> <player> <message>"
